/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PylonOpenCvSwingWrapperJNI {
  public final static native long new_Shape(int jarg1);
  public final static native int Shape_getX(long jarg1, Shape jarg1_);
  public final static native void Shape_setX(long jarg1, Shape jarg1_, int jarg2);
  public final static native void delete_Shape(long jarg1);
}
